import { SKILL_LEVELS, LANGUAGE_LEVELS } from "@/lib/constants";
import { SkillEntry } from "@/lib/profileFields";
import { tagStyle } from "@/lib/jobCardStyles";

const EDUCATION_LABELS: Record<string, string> = {
  none: "بدون مؤهل دراسي",
  literacy: "محو أمية",
  primary: "ابتدائية",
  preparatory: "إعدادية",
  secondary: "ثانوية عامة / دبلوم",
  bachelor: "بكالوريوس/ليسانس",
  master: "ماجستير",
  phd: "دكتوراه",
};

type Props = {
  data: any;
  skills: SkillEntry[];
  languages: SkillEntry[];
  // true لما السيرة الذاتية دي متولّدة تلقائيًا من بيانات البروفايل بدل ما تكون الملف
  // الأصلي اللي رفعه الباحث بنفسه — لازم يبقى واضح لصاحب العمل إنها مش نفس الملف الأصلي.
  autoGenerated?: boolean;
};

export default function CVPreview({ data, skills, languages, autoGenerated }: Props) {
  const workExperience: any[] = Array.isArray(data.workExperience) ? data.workExperience : [];

  return (
    <div style={{ fontFamily: "Tajawal, sans-serif", direction: "rtl", padding: 30, maxWidth: 700, margin: "0 auto", color: "#14213D" }}>
      {autoGenerated && (
        <div
          style={{
            background: "#FDF3E1",
            border: "1px solid #E8A33D66",
            color: "#8A570D",
            borderRadius: 8,
            padding: "10px 14px",
            fontSize: 13,
            fontWeight: 700,
            textAlign: "center",
            marginBottom: 18,
          }}
        >
          ⚠️ سيرة ذاتية تلقائية من بيانات البروفايل — مش الملف الأصلي اللي رفعه الباحث
        </div>
      )}
      <div style={{ display: "flex", alignItems: "center", gap: 16, borderBottom: "3px solid #14213D", paddingBottom: 16, marginBottom: 20 }}>
        {data.photoURL && (
          <img src={data.photoURL} alt={data.fullName || "الصورة الشخصية"} style={{ width: 80, height: 80, objectFit: "cover", borderRadius: "50%", flexShrink: 0 }} />
        )}
        <div>
          <h1 style={{ margin: 0, fontSize: 28 }}>{data.fullName || ""}</h1>
          <p style={{ margin: "6px 0 0", fontSize: 16, color: "#C97F1F", fontWeight: 700 }}>{data.jobTitle || ""}</p>
          <p style={{ margin: "8px 0 0", fontSize: 13, color: "#4A5568" }}>
            📞 {data.phone || "—"} &nbsp;|&nbsp; ✉️ {data.email || "—"} &nbsp;|&nbsp; 📍 {data.city || ""} - {data.governorate || ""} &nbsp;|&nbsp; {data.yearsOfExperience || 0} سنوات خبرة
          </p>
        </div>
      </div>

      {data.bio && (
        <>
          <CVSectionTitle title="نبذة" />
          <p style={{ fontSize: 13.5, color: "#333" }}>{data.bio}</p>
        </>
      )}

      <CVSectionTitle title="الخبرات السابقة" />
      {workExperience.length > 0 ? (
        workExperience.map((e, i) => (
          <div key={i} style={{ marginBottom: 14 }}>
            <div style={{ display: "flex", justifyContent: "space-between", fontWeight: 700 }}>
              <span>{e.jobTitle || ""} — {e.company || ""}</span>
              <span style={{ fontSize: 12, color: "#4A5568" }}>{e.fromDate || ""} - {e.isCurrent ? "الآن" : e.toDate || ""}</span>
            </div>
            {e.responsibilities && <p style={{ margin: "4px 0 0", fontSize: 13, color: "#333" }}>{e.responsibilities}</p>}
          </div>
        ))
      ) : (
        <p style={{ fontSize: 13, color: "#4A5568" }}>لا يوجد</p>
      )}

      <CVSectionTitle title="المؤهل الدراسي" />
      <p style={{ fontSize: 13.5, color: "#333" }}>{EDUCATION_LABELS[data.educationLevel] || data.educationLevel || "—"}</p>

      <CVSectionTitle title="المهارات" />
      {skills.length > 0 ? (
        <div>
          {skills.map((s, i) => (
            <span key={i} style={{ ...tagStyle, display: "inline-block", margin: 2 }}>
              {s.name}
              {s.level && <span style={{ color: "#4A5568" }}> · {SKILL_LEVELS[s.level] || s.level}</span>}
            </span>
          ))}
        </div>
      ) : (
        <p style={{ fontSize: 13, color: "#4A5568" }}>لا يوجد</p>
      )}

      <CVSectionTitle title="اللغات" />
      {languages.length > 0 ? (
        <div>
          {languages.map((l, i) => (
            <span key={i} style={{ ...tagStyle, display: "inline-block", margin: 2 }}>
              {l.name}
              {l.level && <span style={{ color: "#4A5568" }}> · {LANGUAGE_LEVELS[l.level] || l.level}</span>}
            </span>
          ))}
        </div>
      ) : (
        <p style={{ fontSize: 13, color: "#4A5568" }}>لا يوجد</p>
      )}

      <div style={{ marginTop: 30, paddingTop: 14, borderTop: "1px solid #DED2B5", textAlign: "center", fontSize: 11.5, color: "#4A5568" }}>
        {autoGenerated
          ? 'سيرة ذاتية تلقائية متولّدة من بيانات بروفايل الباحث على موقع "الشغل" — elshoghl.com'
          : 'تم إنشاء هذه السيرة الذاتية عبر موقع "الشغل" — elshoghl.com'}
      </div>
    </div>
  );
}

function CVSectionTitle({ title }: { title: string }) {
  return (
    <h3 style={{ fontSize: 15, borderRight: "4px solid #C97F1F", paddingRight: 10, marginTop: 20, marginBottom: 8 }}>
      {title}
    </h3>
  );
}
